# -*- coding: utf-8 -*-
"""Copy of lab-8 RAG .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n49A3MhQrl3K56zrB_cuzXXfNCuygfE3

#**📌Project Description**

This project implements a Retrieval-Augmented Generation (RAG) chatbot that allows users to ask questions about course materials stored in PDF files.
The system retrieves the most relevant document sections using vector similarity search (FAISS) and then generates accurate, context-aware answers using an OpenAI language model.
A simple Gradio chat interface is provided to enable interactive and user-friendly access to the knowledge contained in the PDFs.

#**1 . Setup & Environment**
"""

# Install and update required libraries quietly (-q) to reduce console output
# These libraries are essential for building a Retrieval-Augmented Generation (RAG) pipeline

import gradio as gr

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import PyPDFLoader

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

# Embeddings + LLM (same as your code)
embeddings = OpenAIEmbeddings(model="text-embedding-3-large")
llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0.2)

# Prompt (create it if you already have one, keep yours)
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant. Answer using ONLY the given context."),
    ("human", "Context:\n{context}\n\nQuestion: {question}")
])

def format_docs(docs):
    lines = []
    for d in docs:
        src = d.metadata.get("source", "unknown_source")
        lines.append(f"[SOURCE: {src}]\n{d.page_content}")
    return "\n\n".join(lines)

# Splitter (same settings)
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=900,
    chunk_overlap=150
)

def build_retriever(files):
    # files: uploaded PDFs from Gradio
    if not files:
        return None, "رجاءً ارفع ملف PDF واحد على الأقل."

    docs = []
    try:
        # Load PDFs
        for f in files:
            loader = PyPDFLoader(f.name)   # temp file path from Gradio
            docs.extend(loader.load())

        # Split into chunks
        chunks = text_splitter.split_documents(docs)

        # Build FAISS vectorstore
        vectorstore = FAISS.from_documents(chunks, embeddings)

        # Create retriever (k=4 same as your code)
        retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

        return retriever, f"✅ Loaded {len(docs)} pages | Created {len(chunks)} chunks"
    except Exception as e:
        return None, f"❌ Error while building retriever: {e}"

def chat_fn(message, history, retriever):
    if not message.strip():
        return "Type a question."

    if retriever is None:
        return "ارفع ملفات PDF واضغط Build Index أولًا."

    try:
        rag_chain = (
            {
                "context": retriever | format_docs,
                "question": RunnablePassthrough()
            }
            | prompt
            | llm
            | StrOutputParser()
        )
        return rag_chain.invoke(message)
    except Exception as e:
        return f"Error: {e}"

with gr.Blocks() as demo:
    gr.Markdown("## 📚 GenAI Study Chatbot (RAG)")

    retriever_state = gr.State(None)

    files = gr.File(
        label="Upload PDF(s)",
        file_types=[".pdf"],
        file_count="multiple"
    )

    build_btn = gr.Button("Build Index")
    status = gr.Textbox(label="Status", interactive=False)

    build_btn.click(
        fn=build_retriever,
        inputs=[files],
        outputs=[retriever_state, status]
    )

    gr.ChatInterface(
        fn=chat_fn,
        additional_inputs=[retriever_state],
        title="📚 GenAI Study Chatbot (RAG)",
        description="Upload PDFs → Click Build Index → Ask questions"
    )

demo.launch(share=True)

"""#**2 . Data loading**

#**3 . Text Chunking**
"""

# Split documents into smaller overlapping text chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=900,      # Maximum number of characters per chunk
    chunk_overlap=150    # Overlap between chunks to preserve context
)

# Apply the splitter to the loaded documents
chunks = text_splitter.split_documents(docs)

# Check number of chunks and preview the first one
len(chunks), chunks[0].page_content[:200]

"""#**4 . Embeddings & Vector Store**"""

# Create embedding model to convert text into vectors
embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

# Store document embeddings in a FAISS vector database
vectorstore = FAISS.from_documents(chunks, embeddings)

# Create a retriever to fetch the top 4 most relevant chunks
retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

# Initialize the language model for generating answers
llm = ChatOpenAI(
    model="gpt-4.1-mini",  # Fast and cost-efficient OpenAI chat model
    temperature=0.2       # Low value for more stable and factual responses
)

"""#**5 . Prompting & RAG Chain**"""

prompt = ChatPromptTemplate.from_messages([
    ("system",
     "You are a study chatbot for a university Generative AI course.\n"
     "RULES:\n"
     "1) Answer ONLY using the provided course context.\n"
     "2) If the answer is not in the context, say: 'Not found in course materials.'\n"
     "3) Be clear and student-friendly.\n"
     "4) Always output in this format:\n"
     "Answer:\n"
     "- (your explanation)\n\n"
     "Key points:\n"
     "- ...\n\n"
     "Quick example:\n"
     "- ...\n\n"
     "Sources:\n"
     "- list the source names from metadata if available.\n"
    ),
    ("human",
     "Question: {question}\n\n"
     "Course context:\n{context}")
])

# Format retrieved documents into a single text block
def format_docs(docs):
    lines = []

    # Loop through each retrieved document
    for d in docs:
        # Get document source from metadata (if available)
        src = d.metadata.get("source", "unknown_source")

        # Add source label and document content
        lines.append(f"[SOURCE: {src}]\n{d.page_content}")

    # Join all documents into one string
    return "\n\n".join(lines)

# Build the RAG pipeline
rag_chain = (
    {
        # Retrieve relevant documents and format them as context
        "context": retriever | format_docs,

        # Pass the user question as-is
        "question": RunnablePassthrough()
    }
    # Insert context and question into the prompt
    | prompt

    # Generate an answer using the language model
    | llm

    # Convert the model output to plain text
    | StrOutputParser()
)

questions = [
    "Explain what RAG is and why we use it in study chatbots.",
    "What is temperature in LLMs and how does it affect outputs?",
    "Give me a simple evaluation method to compare two summaries."
]

for q in questions:
    print("="*90)
    print("Q:", q)
    ans = rag_chain.invoke(q)
    print(ans)

import gradio as gr
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import FAISS
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain_core.prompts import ChatPromptTemplate

# --- Models ---
embeddings = OpenAIEmbeddings(model="text-embedding-3-large")
llm = ChatOpenAI(model="gpt-4.1-mini", temperature=0.2)

# --- Prompt (example) ---
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful study assistant. Use ONLY the provided context to answer."),
    ("human", "Context:\n{context}\n\nQuestion: {question}")
])

# --- Helpers ---
def format_docs(docs):
    return "\n\n".join(d.page_content for d in docs)

text_splitter = RecursiveCharacterTextSplitter(chunk_size=900, chunk_overlap=150)

def build_index(files):
    """
    files: list of uploaded files (TemporaryFile-like objects)
    returns: FAISS vectorstore (or error message)
    """
    if not files:
        return None, "رجاءً ارفع ملف PDF واحد على الأقل."

    docs = []
    try:
        for f in files:
            loader = PyPDFLoader(f.name)   # Gradio gives a temp path in f.name
            docs.extend(loader.load())

        chunks = text_splitter.split_documents(docs)
        vs = FAISS.from_documents(chunks, embeddings)

        return vs, f"✅ تم بناء الفهرس بنجاح. Pages: {len(docs)} | Chunks: {len(chunks)}"
    except Exception as e:
        return None, f"❌ خطأ أثناء بناء الفهرس: {e}"

def chat_fn(message, history, vectorstore):
    if not message.strip():
        return "اكتب سؤالًا."
    if vectorstore is None:
        return "ارفع PDF أولًا ثم اضغط Build Index."

    try:
        retriever = vectorstore.as_retriever(search_kwargs={"k": 4})
        rag_chain = (
            {"context": retriever | format_docs, "question": RunnablePassthrough()}
            | prompt
            | llm
            | StrOutputParser()
        )
        return rag_chain.invoke(message)
    except Exception as e:
        return f"Error: {e}"

# --- UI ---
with gr.Blocks() as demo:
    gr.Markdown("## 📚 RAG Chatbot — ارفع ملفاتك واسأل عنها")

    vectorstore_state = gr.State(None)

    with gr.Row():
        files = gr.File(label="Upload PDF(s)", file_types=[".pdf"], file_count="multiple")
        build_btn = gr.Button("Build Index")

    status = gr.Textbox(label="Status", interactive=False)

    build_btn.click(
        fn=build_index,
        inputs=[files],
        outputs=[vectorstore_state, status]
    )

    chat = gr.ChatInterface(
        fn=chat_fn,
        additional_inputs=[vectorstore_state],
        title="💬 اسأل عن ملفاتك",
        description="ارفع PDF ثم اضغط Build Index، بعدها اسأل."
    )

demo.launch(share=True)

"""#**6 . User Interface " GUI - Gradio "**"""


# Import Gradio for building a simple chat interface
import gradio as gr

# Chat function that sends user questions to the RAG pipeline
def chat_fn(message, history):
    # Check if the user input is empty
    if not message.strip():
        return "Type a question."
    try:
        # Generate an answer using the RAG chain
        return rag_chain.invoke(message)
    except Exception as e:
        # Handle and display any errors
        return f"Error: {e}"

# Create a chat interface using Gradio
demo = gr.ChatInterface(
    fn=chat_fn,
    title="📚 GenAI Study Chatbot (RAG)",
    description="Ask questions about the course PDFs in /content/course-materials",
)

# Launch the app (share=True creates a public link)
demo.launch()